### ISSUE TITLE
had sloved ??

### ISSUE THREAD

**Issue by timiil** [meyerson/anbox#1]
hi, just for asking if you had sloved the problem and can make the docker run as expect?

**Comment by meyerson** [comment]
last I played with this was a few months and 'make run' worked - https://github.com/meyerson/anbox/blob/docker_anbox/Makefile

But I would welcome help

**Comment by yuetianle** [comment]
can run anbox in docker ? have the appication manager not reday!! Use the dockerfilework isn't work fine

**Comment by meyerson** [comment]
You have to use the Makefile to make this work @yuetianle  - what exactly did you try?
start by getting the host machine ready
https://github.com/meyerson/anbox/blob/docker_anbox/Makefile#L90
